//
//  LanguagesEnum.swift
//  Galago
//
//  Created by Jared Thorne on 2022-10-04.
//

import Foundation

enum LanguagesEnum: Codable {
    case AFRIKAANS
    case ALBANIAN
    case AMHARIC
    case ARABIC
    case ARMENIAN
    case ASSAMESE
    case AYMARA
    case AZERBAIJANI
    case BAMBARA
    case BASQUE
    case BELARUSIAN
    case BENGALI
    case BHOJPURI
    case BOSNIAN
    case BULGARIAN
    case CATALAN
    case CEBUANO
    case CHICHEQA
    case CHINESE_SIMLIFIED
    case CHINESE_TRADITIONAL
    case CORSICAN
    case CROATIAN
    case CZECH
    case DANISH
    case DHIVEHI
    case DOGRI
    case DUTCH
    case ENGLISH
    case ESPERANTO
    case ESTONIAN
    case EWE
    case FILIPINO
    case FINNISH
    case FRENCH
    case FRISIAN
    case GALACIAN
    case GEORGIAN
    case GERMAN
    case GREEK
    case GUARANI
    case HAITIAN_CREOLE
    case HAUSA
    case HAWAIIAN
    case HEBREW
    case HINDI
    case HMONG
    case HUNGARIAN
    case ICELANDIC
    case IGBO
    case ILOCANO
    case INDONESIAN
    case IRISH
    case ITALIAN
    case JAPANESE
    case JAVANESE
    case KANNADA
    case KAZAKH
    case KHMER
    case KINYARWANDA
    case KONKANI
    case KOREAN
    case KRIO
    case KURDISH_KURMANJI
    case KURDISH_SORANI
    case KYRGYZ
    case LAO
    case LATIN
    case LATVIAN
    case LINGALA
    case LITHUANIAN
    case LUGANDA
    case LUXEMBOURGISH
    case MACEDONIAN
    case MAITHILI
    case MALAGASY
    case MALAY
    case MALAYALAM
    case MALTESE
    case MAORI
    case MARATHI
    case MEITEILON
    case MIZO
    case MONGOLIAN
    case MYANMAR
    case NEPALI
    case NORWEGIAN
    case ODIA
    case OROMO
    case PASHTO
    case PERSIAN
    case POLISH
    case PORTUGUESE
    case PUNJABI
    case QUECHUA
    case ROMANIAN
    case RUSSIAN
    case SAMOAN
    case SANSKRIT
    case SCOTS_GAELIC
    case SEPEDI
    case SERBIAN
    case SESOTHO
    case SHONA
    case SINDHI
    case SINHALA
    case SLOVAK
    case SLOVENIAN
    case SOMALI
    case SPANISH
    case SUNDANESE
    case SWAHLILI
    case SWEDISH
    case TAJIK
    case TAMIL
    case TATAR
    case TELUGU
    case THAI
    case TIGRINYA
    case TSONGA
    case TURKISH
    case TURKMEN
    case TWI
    case UKRAINIAN
    case URDU
    case UYGHUR
    case UZBEK
    case VIETNAMESE
    case WELSH
    case XHOSA
    case YIDDISH
    case YORUBA
    case ZULU
}
